export const MOVE_FORWARD = 'MOVE_FORWARD';
export const ROTATE_CLOCKWISE = 'ROTATE_CLOCKWISE';
export const ROTATE_ANTICLOCKWISE = 'ROTATE_ANTICLOCKWISE';
export const DEFINE_MACRO = 'DEFINE_MACRO';
export const EXEC_MACRO = 'EXEC_MACRO';
export const RESTART = 'RESTART';
